# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on: [ pull_request, push ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ '11' ]
        
    name: JDK ${{ matrix.java }} build
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-jdk${{ matrix.java }}-
    
    - name: Build with Maven
      run: mvn -B clean install

  checkstyle:
    needs: build
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
      - uses: actions/checkout@v2
      - run: mvn -B clean compile jxr:jxr checkstyle:checkstyle
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/checkstyle-result.xml'

  coverage:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '11' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -B clean verify -P coverage --no-transfer-progress

      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov